### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by limingyue123** [sueki743/LWMV3D#2]
我又遇到了下面的问题。。。。。。
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 266, in loader
    self.queue.append(self._load())
  File "train.py", line 229, in _load
    tag = self.tags[self.tag_index]
IndexError: list index out of range

**Comment by limingyue123** [comment]
@sueki743 I need your help!!!!
